// AUTO-GENERATED by gen-providers.mjs from OmniRoute source. Do NOT edit by hand.
// Regenerate: node gen-providers.mjs   (after upgrading OmniRoute — npm global or git-clone under External/)
// web=23  apikey=167  oauth=18
const OMNI_GEN = {
  web: [
 {
  "slug": "claude-web",
  "label": "Claude Web",
  "site": "https://claude.ai",
  "loginUrl": "https://claude.ai/login",
  "host": "claude.ai",
  "perms": [
   "https://claude.ai/*",
   "https://*.claude.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?claude\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "sessionKey",
    "domain": ".claude.ai"
   }
  ]
 },
 {
  "slug": "chatgpt-web",
  "label": "ChatGPT Web",
  "site": "https://chatgpt.com",
  "loginUrl": "https://chatgpt.com/auth/login",
  "host": "chatgpt.com",
  "perms": [
   "https://chatgpt.com/*",
   "https://*.chatgpt.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?chatgpt\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "__Secure-next-auth.session-token",
    "domain": ".chatgpt.com"
   }
  ]
 },
 {
  "slug": "gemini-web",
  "label": "Gemini Web",
  "site": "https://gemini.google.com",
  "loginUrl": "https://gemini.google.com/app",
  "host": "gemini.google.com",
  "perms": [
   "https://gemini.google.com/*"
  ],
  "hostReSrc": "^https://gemini\\.google\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "__Secure-1PSID",
    "domain": ".google.com"
   },
   {
    "type": "cookie",
    "name": "__Secure-1PSIDTS",
    "domain": ".google.com"
   }
  ]
 },
 {
  "slug": "grok-web",
  "label": "Grok Web",
  "site": "https://grok.com",
  "loginUrl": "https://grok.com/login",
  "host": "grok.com",
  "perms": [
   "https://grok.com/*",
   "https://*.grok.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?grok\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "sso",
    "domain": ".grok.com"
   }
  ]
 },
 {
  "slug": "perplexity-web",
  "label": "Perplexity Web",
  "site": "https://www.perplexity.ai",
  "loginUrl": "https://www.perplexity.ai/login",
  "host": "www.perplexity.ai",
  "perms": [
   "https://www.perplexity.ai/*",
   "https://*.perplexity.ai/*",
   "https://perplexity.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?perplexity\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "__Secure-next-auth.session-token",
    "domain": ".perplexity.ai"
   }
  ]
 },
 {
  "slug": "deepseek-web",
  "label": "DeepSeek Web",
  "site": "https://chat.deepseek.com",
  "loginUrl": "https://chat.deepseek.com/sign_in",
  "host": "chat.deepseek.com",
  "perms": [
   "https://chat.deepseek.com/*",
   "https://*.deepseek.com/*",
   "https://deepseek.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?deepseek\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "user-token",
    "domain": ".deepseek.com"
   },
   {
    "type": "localStorage",
    "name": "userToken"
   }
  ]
 },
 {
  "slug": "qwen-web",
  "label": "Qwen Web (Tongyi)",
  "site": "https://chat.qwen.ai",
  "loginUrl": "https://chat.qwen.ai/",
  "host": "chat.qwen.ai",
  "perms": [
   "https://chat.qwen.ai/*",
   "https://*.qwen.ai/*",
   "https://qwen.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?qwen\\.ai/",
  "sources": [
   {
    "type": "localStorage",
    "name": "token"
   },
   {
    "type": "cookie",
    "name": "token",
    "domain": ".chat.qwen.ai"
   },
   {
    "type": "cookie",
    "name": "cna",
    "domain": ".chat.qwen.ai"
   },
   {
    "type": "cookie",
    "name": "ssxmod_itna",
    "domain": ".chat.qwen.ai"
   },
   {
    "type": "cookie",
    "name": "ssxmod_itna2",
    "domain": ".chat.qwen.ai"
   },
   {
    "type": "cookie",
    "name": "XSRF_TOKEN",
    "domain": ".chat.qwen.ai"
   }
  ]
 },
 {
  "slug": "kimi-web",
  "label": "Kimi (Moonshot)",
  "site": "https://www.kimi.com",
  "loginUrl": "https://www.kimi.com/",
  "host": "www.kimi.com",
  "perms": [
   "https://www.kimi.com/*",
   "https://*.kimi.com/*",
   "https://kimi.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?kimi\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "kimi-auth",
    "domain": ".kimi.com"
   }
  ]
 },
 {
  "slug": "blackbox-web",
  "label": "Blackbox AI",
  "site": "https://app.blackbox.ai",
  "loginUrl": "https://app.blackbox.ai/login",
  "host": "app.blackbox.ai",
  "perms": [
   "https://app.blackbox.ai/*",
   "https://*.blackbox.ai/*",
   "https://blackbox.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?blackbox\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "connect.sid",
    "domain": ".blackbox.ai"
   },
   {
    "type": "localStorage",
    "name": "token"
   }
  ]
 },
 {
  "slug": "poe-web",
  "label": "Poe (Quora)",
  "site": "https://poe.com",
  "loginUrl": "https://poe.com/login",
  "host": "poe.com",
  "perms": [
   "https://poe.com/*",
   "https://*.poe.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?poe\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "p-b",
    "domain": ".poe.com"
   }
  ]
 },
 {
  "slug": "copilot-web",
  "label": "Microsoft Copilot",
  "site": "https://copilot.microsoft.com",
  "loginUrl": "https://copilot.microsoft.com/",
  "host": "copilot.microsoft.com",
  "perms": [
   "https://copilot.microsoft.com/*"
  ],
  "hostReSrc": "^https://copilot\\.microsoft\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "RPSCAuth",
    "domain": ".microsoft.com"
   }
  ]
 },
 {
  "slug": "doubao-web",
  "label": "Dola (ByteDance)",
  "site": "https://www.dola.com",
  "loginUrl": "https://www.dola.com/",
  "host": "www.dola.com",
  "perms": [
   "https://www.dola.com/*",
   "https://*.dola.com/*",
   "https://dola.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?dola\\.com/",
  "sources": [
   {
    "type": "cookie",
    "name": "sessionid",
    "domain": ".dola.com"
   },
   {
    "type": "cookie",
    "name": "ttwid",
    "domain": ".dola.com"
   },
   {
    "type": "cookie",
    "name": "s_v_web_id",
    "domain": ".dola.com"
   }
  ]
 },
 {
  "slug": "venice-web",
  "label": "Venice AI",
  "site": "https://venice.ai",
  "loginUrl": "https://venice.ai/login",
  "host": "venice.ai",
  "perms": [
   "https://venice.ai/*",
   "https://*.venice.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?venice\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "venice_session",
    "domain": ".venice.ai"
   },
   {
    "type": "localStorage",
    "name": "token"
   }
  ]
 },
 {
  "slug": "v0-vercel-web",
  "label": "v0 by Vercel",
  "site": "https://v0.dev",
  "loginUrl": "https://v0.dev/login",
  "host": "v0.dev",
  "perms": [
   "https://v0.dev/*",
   "https://*.v0.dev/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?v0\\.dev/",
  "sources": [
   {
    "type": "cookie",
    "name": "__Secure-next-auth.session-token",
    "domain": ".v0.dev"
   }
  ]
 },
 {
  "slug": "muse-spark-web",
  "label": "Meta AI (Muse)",
  "site": "https://www.meta.ai",
  "loginUrl": "https://www.meta.ai/",
  "host": "www.meta.ai",
  "perms": [
   "https://www.meta.ai/*",
   "https://*.meta.ai/*",
   "https://meta.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?meta\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "session",
    "domain": ".meta.ai"
   }
  ]
 },
 {
  "slug": "adapta-web",
  "label": "Adapta AI",
  "site": "https://agent.adapta.one",
  "loginUrl": "https://agent.adapta.one/login",
  "host": "agent.adapta.one",
  "perms": [
   "https://agent.adapta.one/*",
   "https://*.adapta.one/*",
   "https://adapta.one/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?adapta\\.one/",
  "sources": [
   {
    "type": "cookie",
    "name": "__session",
    "domain": ".adapta.one"
   }
  ]
 },
 {
  "slug": "zai-web",
  "label": "Z.ai Web (Free)",
  "site": "https://chat.z.ai",
  "loginUrl": "https://chat.z.ai/",
  "host": "chat.z.ai",
  "perms": [
   "https://chat.z.ai/*",
   "https://*.z.ai/*",
   "https://z.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?z\\.ai/",
  "sources": [
   {
    "type": "cookie",
    "name": "token",
    "domain": ".z.ai"
   }
  ]
 },
 {
  "slug": "huggingchat",
  "label": "HuggingChat",
  "site": "https://huggingface.co",
  "loginUrl": "https://huggingface.co/chat",
  "host": "huggingface.co",
  "perms": [
   "https://huggingface.co/*",
   "https://*.huggingface.co/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?huggingface\\.co/",
  "sources": []
 },
 {
  "slug": "lmarena",
  "label": "LMArena",
  "site": "https://lmarena.ai",
  "loginUrl": "https://lmarena.ai",
  "host": "lmarena.ai",
  "perms": [
   "https://lmarena.ai/*",
   "https://*.lmarena.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?lmarena\\.ai/",
  "sources": []
 },
 {
  "slug": "zenmux-free",
  "label": "ZenMux (Free)",
  "site": "https://zenmux.ai",
  "loginUrl": "https://zenmux.ai",
  "host": "zenmux.ai",
  "perms": [
   "https://zenmux.ai/*",
   "https://*.zenmux.ai/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?zenmux\\.ai/",
  "sources": []
 },
 {
  "slug": "inner-ai",
  "label": "InnerAI",
  "site": "https://app.innerai.com",
  "loginUrl": "https://app.innerai.com",
  "host": "app.innerai.com",
  "perms": [
   "https://app.innerai.com/*",
   "https://*.innerai.com/*",
   "https://innerai.com/*"
  ],
  "hostReSrc": "^https://([\\w-]+\\.)?innerai\\.com/",
  "sources": []
 },
 {
  "slug": "yuanbao-web",
  "label": "Tencent Yuanbao",
  "site": "https://yuanbao.tencent.com",
  "loginUrl": "https://yuanbao.tencent.com",
  "host": "yuanbao.tencent.com",
  "perms": [
   "https://yuanbao.tencent.com/*"
  ],
  "hostReSrc": "^https://yuanbao\\.tencent\\.com/",
  "sources": []
 },
 {
  "slug": "copilot-m365-web",
  "label": "MS Copilot (M365)",
  "site": "https://m365.cloud.microsoft",
  "loginUrl": "https://m365.cloud.microsoft",
  "host": "m365.cloud.microsoft",
  "perms": [
   "https://m365.cloud.microsoft/*"
  ],
  "hostReSrc": "^https://m365\\.cloud\\.microsoft/",
  "sources": []
 }
],
  apikey: [
 {
  "slug": "azure-openai",
  "label": "Azure OpenAI",
  "get": "https://azure.microsoft.com/products/ai-services/openai-service",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "azure-ai",
  "label": "Azure AI Foundry",
  "get": "https://learn.microsoft.com/azure/ai-foundry",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "bedrock",
  "label": "Amazon Bedrock",
  "get": "https://aws.amazon.com/bedrock",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "watsonx",
  "label": "IBM watsonx.ai Gateway",
  "get": "https://www.ibm.com/products/watsonx-ai",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "oci",
  "label": "OCI Generative AI",
  "get": "https://www.oracle.com/artificial-intelligence/generative-ai",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "sap",
  "label": "SAP Generative AI Hub",
  "get": "https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/generative-ai-hub-in-sap-ai-core",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "modal",
  "label": "Modal",
  "get": "https://modal.com/docs",
  "free": true,
  "family": "Enterprise / облака"
 },
 {
  "slug": "vertex",
  "label": "Vertex AI",
  "get": "https://cloud.google.com/vertex-ai",
  "free": true,
  "family": "Enterprise / облака"
 },
 {
  "slug": "vertex-partner",
  "label": "Vertex AI Partners",
  "get": "https://cloud.google.com/vertex-ai",
  "free": true,
  "family": "Enterprise / облака"
 },
 {
  "slug": "cloudflare-ai",
  "label": "Cloudflare Workers AI",
  "get": "https://developers.cloudflare.com/workers-ai",
  "free": true,
  "family": "Enterprise / облака"
 },
 {
  "slug": "scaleway",
  "label": "Scaleway AI",
  "get": "https://www.scaleway.com/en/docs/ai-data/generative-apis/",
  "free": true,
  "family": "Enterprise / облака"
 },
 {
  "slug": "ovhcloud",
  "label": "OVHcloud AI",
  "get": "https://www.ovhcloud.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "heroku",
  "label": "Heroku AI",
  "get": "https://www.heroku.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "databricks",
  "label": "Databricks",
  "get": "https://www.databricks.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "datarobot",
  "label": "DataRobot",
  "get": "https://docs.datarobot.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "clarifai",
  "label": "Clarifai",
  "get": "https://docs.clarifai.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "snowflake",
  "label": "Snowflake Cortex",
  "get": "https://www.snowflake.com",
  "free": false,
  "family": "Enterprise / облака"
 },
 {
  "slug": "openai",
  "label": "OpenAI",
  "get": "https://platform.openai.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "reka",
  "label": "Reka",
  "get": "https://docs.reka.ai/chat/overview",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "pioneer",
  "label": "Pioneer AI",
  "get": "https://pioneer.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "anthropic",
  "label": "Anthropic",
  "get": "https://platform.claude.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "gemini",
  "label": "Gemini (Google AI Studio)",
  "get": "https://aistudio.google.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "groq",
  "label": "Groq",
  "get": "https://groq.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "blackbox",
  "label": "Blackbox AI",
  "get": "https://blackbox.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "xai",
  "label": "xAI (Grok)",
  "get": "https://x.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "mistral",
  "label": "Mistral",
  "get": "https://mistral.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "perplexity",
  "label": "Perplexity",
  "get": "https://www.perplexity.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "cohere",
  "label": "Cohere",
  "get": "https://cohere.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "meta-llama",
  "label": "Meta Llama API",
  "get": "https://llama.developer.meta.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "morph",
  "label": "Morph",
  "get": "https://morphllm.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "galadriel",
  "label": "Galadriel",
  "get": "https://galadriel.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "ai21",
  "label": "AI21 Labs",
  "get": "https://www.ai21.com",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "venice",
  "label": "Venice.ai",
  "get": "https://venice.ai",
  "free": false,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "codestral",
  "label": "Codestral",
  "get": "https://mistral.ai",
  "free": false,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "upstage",
  "label": "Upstage",
  "get": "https://www.upstage.ai",
  "free": false,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "maritalk",
  "label": "Maritalk",
  "get": "https://www.maritaca.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "nous-research",
  "label": "Nous Research",
  "get": "https://portal.nousresearch.com/help",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "arcee-ai",
  "label": "Arcee AI",
  "get": "https://arcee.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "liquid",
  "label": "Liquid AI",
  "get": "https://liquid.ai",
  "free": true,
  "family": "Frontier-лаборатории"
 },
 {
  "slug": "charm-hyper",
  "label": "Charm Hyper",
  "get": "https://hyper.charm.land",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "agentrouter",
  "label": "AgentRouter",
  "get": "https://agentrouter.org",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "command-code",
  "label": "Command Code",
  "get": "https://commandcode.ai/",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "openrouter",
  "label": "OpenRouter",
  "get": "https://openrouter.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "requesty",
  "label": "Requesty",
  "get": "https://requesty.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "dgrid",
  "label": "DGrid",
  "get": "https://dgrid.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "qiniu",
  "label": "Qiniu",
  "get": "https://www.qiniu.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "orcarouter",
  "label": "OrcaRouter",
  "get": "https://www.orcarouter.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "api-airforce",
  "label": "Api.airforce",
  "get": "https://api.airforce",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "crof",
  "label": "CrofAI",
  "get": "https://crof.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "bazaarlink",
  "label": "BazaarLink",
  "get": "https://bazaarlink.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "synthetic",
  "label": "Synthetic",
  "get": "https://synthetic.new",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "kilo-gateway",
  "label": "Kilo Gateway",
  "get": "https://kilo.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "wafer",
  "label": "Wafer AI",
  "get": "https://wafer.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "opencode-zen",
  "label": "OpenCode Zen",
  "get": "https://opencode.ai/zen",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "opencode-go",
  "label": "OpenCode Go",
  "get": "https://opencode.ai/go",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "puter",
  "label": "Puter AI",
  "get": "https://puter.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "uncloseai",
  "label": "UncloseAI",
  "get": "https://uncloseai.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "hackclub",
  "label": "Hackclub AI",
  "get": "https://ai.hackclub.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "vercel-ai-gateway",
  "label": "Vercel AI Gateway",
  "get": "https://vercel.com/docs/ai-gateway",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "llm7",
  "label": "LLM7.io",
  "get": "https://llm7.io",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "llamagate",
  "label": "LlamaGate",
  "get": "https://llamagate.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "gitlawb",
  "label": "Gitlawb Opengateway (MiMo)",
  "get": "https://opengateway.gitlawb.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "gitlawb-gmi",
  "label": "Gitlawb Opengateway (GMI Cloud)",
  "get": "https://opengateway.gitlawb.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "nanogpt",
  "label": "NanoGPT",
  "get": "https://nano-gpt.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "aimlapi",
  "label": "AI/ML API",
  "get": "https://aimlapi.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "novita",
  "label": "Novita AI",
  "get": "https://novita.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "piapi",
  "label": "PiAPI",
  "get": "https://piapi.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "getgoapi",
  "label": "GoAPI",
  "get": "https://api.getgoapi.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "laozhang",
  "label": "LaoZhang AI",
  "get": "https://api.laozhang.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "thebai",
  "label": "TheB.AI",
  "get": "https://theb.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "bai",
  "label": "b.ai",
  "get": "https://b.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "fenayai",
  "label": "FenayAI",
  "get": "https://fenayai.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "empower",
  "label": "Empower",
  "get": "https://docs.empower.dev",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "poe",
  "label": "Poe",
  "get": "https://creator.poe.com/api-reference",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "chutes",
  "label": "Chutes.ai",
  "get": "https://chutes.ai",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "factory",
  "label": "Factory",
  "get": "https://factory.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "bluesminds",
  "label": "BluesMinds",
  "get": "https://www.bluesminds.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "freemodel-dev",
  "label": "FreeModel.dev",
  "get": "https://freemodel.dev",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "freeaiapikey",
  "label": "FreeAIAPIKey",
  "get": "https://freeaiapikey.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "zenmux",
  "label": "ZenMux",
  "get": "https://zenmux.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "openadapter",
  "label": "OpenAdapter",
  "get": "https://openadapter.dev",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "dit",
  "label": "DIT.ai",
  "get": "https://dit.ai",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "tokenrouter",
  "label": "TokenRouter",
  "get": "https://tokenrouter.com",
  "free": true,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "sumopod",
  "label": "SumoPod",
  "get": "https://ai.sumopod.com",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "x5lab",
  "label": "X5Lab",
  "get": "https://x5lab.dev",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "kenari",
  "label": "Kenari",
  "get": "https://kenari.id",
  "free": false,
  "family": "Шлюзы и агрегаторы"
 },
 {
  "slug": "together",
  "label": "Together AI",
  "get": "https://www.together.ai",
  "free": false,
  "family": "Inference-хосты"
 },
 {
  "slug": "openvecta",
  "label": "OpenVecta",
  "get": "https://openvecta.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "fireworks",
  "label": "Fireworks AI",
  "get": "https://fireworks.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "cerebras",
  "label": "Cerebras",
  "get": "https://inference.cerebras.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "nvidia",
  "label": "NVIDIA NIM",
  "get": "https://build.nvidia.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "nebius",
  "label": "Nebius AI",
  "get": "https://nebius.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "nube",
  "label": "Nube.sh",
  "get": "https://nube.sh",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "siliconflow",
  "label": "SiliconFlow",
  "get": "https://cloud.siliconflow.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "hyperbolic",
  "label": "Hyperbolic",
  "get": "https://hyperbolic.xyz",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "ollama-cloud",
  "label": "Ollama Cloud",
  "get": "https://ollama.com/settings/keys",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "huggingface",
  "label": "HuggingFace",
  "get": "https://huggingface.co",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "github-models",
  "label": "GitHub Models",
  "get": "https://github.com/marketplace/models",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "deepinfra",
  "label": "DeepInfra",
  "get": "https://deepinfra.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "lambda-ai",
  "label": "Lambda AI",
  "get": "https://lambda.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "sambanova",
  "label": "SambaNova",
  "get": "https://sambanova.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "nscale",
  "label": "nScale",
  "get": "https://nscale.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "baseten",
  "label": "Baseten",
  "get": "https://baseten.co",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "publicai",
  "label": "PublicAI",
  "get": "https://publicai.co",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "featherless-ai",
  "label": "Featherless AI",
  "get": "https://featherless.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "friendliai",
  "label": "FriendliAI",
  "get": "https://friendli.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "wandb",
  "label": "Weights & Biases Inference",
  "get": "https://wandb.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "inference-net",
  "label": "Inference.net",
  "get": "https://inference.net",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "predibase",
  "label": "Predibase",
  "get": "https://predibase.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "bytez",
  "label": "Bytez",
  "get": "https://bytez.com",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "monsterapi",
  "label": "MonsterAPI",
  "get": "https://monsterapi.ai",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "modelscope",
  "label": "ModelScope",
  "get": "https://modelscope.cn",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "byteplus",
  "label": "BytePlus ModelArk",
  "get": "https://console.byteplus.com/ark",
  "free": true,
  "family": "Inference-хосты"
 },
 {
  "slug": "digitalocean",
  "label": "DigitalOcean",
  "get": "https://docs.digitalocean.com/products/ai-platform/",
  "free": false,
  "family": "Inference-хосты"
 },
 {
  "slug": "qianfan",
  "label": "Baidu Qianfan",
  "get": "https://cloud.baidu.com/product/wenxinworkshop",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "glm",
  "label": "GLM Coding",
  "get": "https://z.ai/subscribe",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "glm-cn",
  "label": "GLM Coding (China)",
  "get": "https://open.bigmodel.cn",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "glmt",
  "label": "GLM Thinking",
  "get": "https://open.bigmodel.cn",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "bailian-coding-plan",
  "label": "Alibaba Coding Plan",
  "get": "https://www.alibabacloud.com/help/en/model-studio/coding-plan",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "kimi",
  "label": "Kimi",
  "get": "https://platform.moonshot.ai",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "kimi-coding-apikey",
  "label": "Kimi Coding (API Key)",
  "get": "https://www.kimi.com/code",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "minimax",
  "label": "Minimax Coding",
  "get": "https://www.minimax.io",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "minimax-cn",
  "label": "Minimax (China)",
  "get": "https://www.minimaxi.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "deepseek",
  "label": "DeepSeek",
  "get": "https://platform.deepseek.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "zai",
  "label": "Z.AI",
  "get": "https://open.bigmodel.cn",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "alibaba",
  "label": "Alibaba",
  "get": "https://bailian.console.alibabacloud.com/",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "alibaba-cn",
  "label": "Alibaba (China)",
  "get": "https://dashscope.console.aliyun.com/",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "longcat",
  "label": "LongCat AI",
  "get": "https://longcat.chat/platform/docs",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "moonshot",
  "label": "Moonshot AI",
  "get": "https://platform.moonshot.ai",
  "free": false,
  "family": "Региональные"
 },
 {
  "slug": "volcengine",
  "label": "Volcengine",
  "get": "https://www.volcengine.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "gigachat",
  "label": "GigaChat (Sber)",
  "get": "https://developers.sber.ru",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "xiaomi-mimo",
  "label": "Xiaomi MiMo",
  "get": "https://mimo.mi.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "baidu",
  "label": "Baidu (ERNIE)",
  "get": "https://yiyan.baidu.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "tencent",
  "label": "Tencent Hunyuan",
  "get": "https://hunyuan.tencent.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "iflytek",
  "label": "iFlytek Spark",
  "get": "https://xinghuo.xfyun.cn",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "baichuan",
  "label": "Baichuan",
  "get": "https://baichuan.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "yi",
  "label": "Yi (01.AI)",
  "get": "https://01.ai",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "stepfun",
  "label": "StepFun",
  "get": "https://stepfun.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "coze",
  "label": "Coze",
  "get": "https://coze.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "360ai",
  "label": "360 AI",
  "get": "https://ai.360.cn",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "doubao",
  "label": "Doubao",
  "get": "https://doubao.com",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "sensenova",
  "label": "SenseNova",
  "get": "https://platform.sensenova.cn",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "sparkdesk",
  "label": "SparkDesk",
  "get": "https://xinghuo.xfyun.cn",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "hcnsec",
  "label": "Huancheng Public API",
  "get": "https://api.hcnsec.cn",
  "free": true,
  "family": "Региональные"
 },
 {
  "slug": "nlpcloud",
  "label": "NLP Cloud",
  "get": "https://docs.nlpcloud.com",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "runwayml",
  "label": "Runway",
  "get": "https://docs.dev.runwayml.com",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "kie",
  "label": "KIE.AI",
  "get": "https://kie.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "pollinations",
  "label": "Pollinations AI",
  "get": "https://pollinations.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "haiper",
  "label": "Haiper",
  "get": "https://haiper.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "leonardo",
  "label": "Leonardo AI",
  "get": "https://leonardo.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "ideogram",
  "label": "Ideogram",
  "get": "https://ideogram.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "suno",
  "label": "Suno",
  "get": "https://suno.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "udio",
  "label": "Udio",
  "get": "https://udio.com",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "v0-vercel",
  "label": "v0 (Vercel)",
  "get": "https://v0.dev",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "gitlab",
  "label": "GitLab Duo PAT",
  "get": "https://docs.gitlab.com/user/duo_agent_platform/code_suggestions/",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "voyage-ai",
  "label": "Voyage AI",
  "get": "https://www.voyageai.com",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "jina-ai",
  "label": "Jina AI",
  "get": "https://jina.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "fal-ai",
  "label": "Fal.ai",
  "get": "https://fal.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "stability-ai",
  "label": "Stability AI",
  "get": "https://stability.ai",
  "free": false,
  "family": "Медиа и спец"
 },
 {
  "slug": "black-forest-labs",
  "label": "Black Forest Labs",
  "get": "https://blackforestlabs.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "recraft",
  "label": "Recraft",
  "get": "https://recraft.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "topaz",
  "label": "Topaz",
  "get": "https://topazlabs.com",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "dify",
  "label": "Dify",
  "get": "https://dify.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "nomic",
  "label": "Nomic",
  "get": "https://nomic.ai",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "firecrawl",
  "label": "Firecrawl",
  "get": "https://firecrawl.dev",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "jina-reader",
  "label": "Jina Reader",
  "get": "https://jina.ai/reader",
  "free": true,
  "family": "Медиа и спец"
 },
 {
  "slug": "tinyfish",
  "label": "TinyFish Fetch",
  "get": "https://docs.tinyfish.ai/fetch-api",
  "free": false,
  "family": "Медиа и спец"
 }
],
  oauth: [
 {
  "slug": "antigravity",
  "label": "antigravity",
  "flowType": "authorization_code"
 },
 {
  "slug": "claude",
  "label": "claude",
  "flowType": "authorization_code_pkce"
 },
 {
  "slug": "cline",
  "label": "cline",
  "flowType": "authorization_code"
 },
 {
  "slug": "codebuddy-cn",
  "label": "codebuddy-cn",
  "flowType": "device_code"
 },
 {
  "slug": "codex",
  "label": "codex",
  "flowType": "authorization_code_pkce"
 },
 {
  "slug": "cursor",
  "label": "cursor",
  "flowType": "import_token"
 },
 {
  "slug": "github",
  "label": "github",
  "flowType": "device_code"
 },
 {
  "slug": "gitlab-duo",
  "label": "gitlab-duo",
  "flowType": "authorization_code_pkce"
 },
 {
  "slug": "grok-cli",
  "label": "grok-cli",
  "flowType": "import_token"
 },
 {
  "slug": "kilocode",
  "label": "kilocode",
  "flowType": "device_code"
 },
 {
  "slug": "kimi-coding",
  "label": "kimi-coding",
  "flowType": "device_code"
 },
 {
  "slug": "kiro",
  "label": "kiro",
  "flowType": "device_code"
 },
 {
  "slug": "qoder",
  "label": "qoder",
  "flowType": "authorization_code"
 },
 {
  "slug": "qwen",
  "label": "qwen",
  "flowType": "device_code"
 },
 {
  "slug": "trae",
  "label": "trae",
  "flowType": "import_token"
 },
 {
  "slug": "windsurf",
  "label": "windsurf",
  "flowType": "import_token"
 },
 {
  "slug": "zed-hosted",
  "label": "zed-hosted",
  "flowType": "authorization_code"
 },
 {
  "slug": "zed",
  "label": "zed",
  "flowType": "import_token"
 }
],
};
if (typeof self !== "undefined") self.OMNI_GEN = OMNI_GEN;
if (typeof module !== "undefined") module.exports = OMNI_GEN;
